### PR TITLE
Fix empty string and GoRun -F main module

### LINKED ISSUE #146: GoRun GoTest errors
I've been playing with `GoRun` and `GoTest` and noticed a few bugs;

~~* (GoTest) if you set a non-default runner, e.g. richgo, and run only `GoTest` without any args, it installs it, and runs the test. But next time around it has to install it again, and the binary is also not callable from anywhere else. So it only does a temporary install.~~ (bug on my side)
* (GoTest) if you pass in the `-F` flag, and have a non-default test runner. It does install it, but only after printing out an error about it not being found. Then opens the terminal prior to it being installed, and then never actually runs the tests.
* (Both) If you pass in the `-F` flag, and an error occurs, the floating term still opens up empty even though an error occurred. Would be nice to have a check that if an error occurred, don't open floating term anymore.

### PR DESCRIPTION
**Pull request by Davincible**
- fix: append check if val is nil Add check to see if value is empty. And don't add to path if already in path.
- feat: auto run main module in floating term Add check to see if floating term, to auto run main file

fix #146

### CODE REVIEW

File: lua/go/asyncmake.lua [hunk 1]
```diff
@@ -118,7 +118,8 @@ function M.make(...)
   end
   if makeprg:find("go run") then
     runner = "go run"
-    if args == nil or #args == 0 then
+    vim.notify(vim.inspect(args))
+    if args == nil or #args == 0 or (#args == 1 and args[1] == "-F") then
```
Comment (ray-x) [inline lua/go/asyncmake.lua:121]: I see what your mean. Thanks.

**Review by ray-x — APPROVED** [review]
LGTM

**Review by ray-x — APPROVED** [review]
LGTM, thanks
